# Generated by Django 3.2.16 on 2022-12-10 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 18, 20, 6, 754579)),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED'), ('PENDING PAYMENT', 'PENDING PAYMENT'), ('ORDER-PLACED', 'ORDER-PLACED'), ('IN-TRANSIT', 'IN-TRANSIT'), ('DELIVERED', 'DELIVERED')], default='ORDER-PLACED', max_length=200, null=True),
        ),
    ]
